<header class="foo_header">
	<div class="container">
		<div class="row">
			<div class="foo_header_links left">
				<ul>
					<li>
						<a href="#">
							<i class="fas fa-map-marker-alt"></i>
							Select Location
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-hotel"></i>
							Restaurants
						</a>
					</li>
				</ul>
			</div>
			<div class="foo_header_logo">
				<a href="#" class="logo">

					<img src="<?php echo $this->getViewFileUrl('Ced_CustomSearchWork::images/logo.png'); ?>" alt="Demo" class="logo-image">
				</a>
			</div>
			<div class="foo_header_links right">
				<ul>
					<li>
						<a href="#">
							<i class="fas fa-search"></i>
							Search
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-sign-in-alt"></i>
							Login
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-sign-in-alt"></i>
							Signup
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-shopping-cart"></i>
							Cart
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</header>
